version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: japrojah/foodgram_backend:latest
   # build:
   #   context: ../backend
   #   dockerfile: Dockerfile
    volumes:
      - static_value:/app/static/
      - media_value:/media
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: japrojah/foodgram_frontend:latest
    #build:
     # context: ../frontend
     # dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/media
    depends_on:
      - frontend
