name: Main Taski Workflow

on: [push]

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print project tree
        run: tree .
###Здесь будут команды для деплоя и пуша на яндекс облако

#  deploy:


#  send_message:
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#    - name: send message
#      uses: appleboy/telegram-action@master
#      with:
#        to: ${{ secrets.TELEGRAM_TO }}
#        token: ${{ secrets.TELEGRAM_TOKEN }}
#        message: Деплой успешно выполнен!
